const BodyContent = [
  [
    "Barton ipsum dolor sit amet consectetur adipisicing elit. Natus facilis rerum sint accusantium? Blanditiis voluptates cum qui, quas eveniet iste. Qui hic incidunt cumque corporis adipisci cupiditate tenetur quisquam. Ea consequatur sunt illo beatae cumque accusamus nostrum similique! Natus porro minus dolor vel obcaecati deserunt hic deleniti maxime iure totam!",

    "Clint Barton was locked in the cell at the investigation site, while Nick Fury ordered scientists to examine Thor's body, learning that Thor was not a human. Phil Coulson told Fury that Barton insisted that he did not kill Thor and he never misfires, no matter what evidence S.H.I.E.L.D. had against him. While Barton was in the cell, Yellowjacket killed him by flying into his ear and causing a hemorrhage in his brain.",

    "Clint and Natasha are best friends. However, at the start of their relationship, Clint Barton (as Hawkeye) was sent to eliminate Natasha, but instead, Barton saw her skills and recommended her recruitment. The two began an everlasting partnership, with Barton affectionately calling her Nat.During The Avengers, Barton was taken by Loki Laufeyson, while being under his mind control. When she heard he was in danger, she immediately beat up her interogators.",
    "Barton has trained himself to become a master archer specializing in the use of regular bows, longbows, compound bows, and crossbows with near-perfect accuracy. He is capable of firing multiple arrows at a single target in a few seconds, hitting multiple targets in a few quick strokes, and directly hit small targets in the greatest of distances. Barton has even been known to hit an apple in the center of it. He practices a minimum of two hours per day to keep his skills honed.",
    "As Hawkeye, Barton possesses a custom-made bow, quick-release quiver, a number of trick arrows and a combat knife. Although he is not known to use melee weapons, Barton's incredible reflexes and hand-eye coordination allow him to easily master most weapons. He also received training in swordsmanship during his youth from the original Swordsman, who was considered one of the greatest experts in sword-fighting the world has ever known. Barton is skilled with swords, knives, nunchakus, staffs, and is one of the few people to be able to properly handle Captain America's shield",

    "Although Hawkeye became romantically involved with the Black Widow, he was unhappy being a criminal. When he approached the Avengers and told them of his desire to reform, Iron Man sponsored his membership on the team. Barton formed, along with Captain America, Scarlet Witch and her brother, Quicksilver, an incarnation of the Avengers known as Cap's Kooky Quartet. Eventually, however, Hawkeye came to respect Cap more than any other Avenger and became one of his staunchest supporters.",
  ],
  [
    "Captain ipsum dolor sit amet consectetur adipisicing elit. Natus facilis rerum sint accusantium? Blanditiis voluptates cum qui, quas eveniet iste. Qui hic incidunt cumque corporis adipisci cupiditate tenetur quisquam. Ea consequatur sunt illo beatae cumque accusamus nostrum similique! Natus porro minus dolor vel obcaecati deserunt hic deleniti maxime iure totam!",

    "Clint Barton was locked in the cell at the investigation site, while Nick Fury ordered scientists to examine Thor's body, learning that Thor was not a human. Phil Coulson told Fury that Barton insisted that he did not kill Thor and he never misfires, no matter what evidence S.H.I.E.L.D. had against him. While Barton was in the cell, Yellowjacket killed him by flying into his ear and causing a hemorrhage in his brain.",

    "Clint and Natasha are best friends. However, at the start of their relationship, Clint Barton (as Hawkeye) was sent to eliminate Natasha, but instead, Barton saw her skills and recommended her recruitment. The two began an everlasting partnership, with Barton affectionately calling her Nat.During The Avengers, Barton was taken by Loki Laufeyson, while being under his mind control. When she heard he was in danger, she immediately beat up her interogators.",
    "Barton has trained himself to become a master archer specializing in the use of regular bows, longbows, compound bows, and crossbows with near-perfect accuracy. He is capable of firing multiple arrows at a single target in a few seconds, hitting multiple targets in a few quick strokes, and directly hit small targets in the greatest of distances. Barton has even been known to hit an apple in the center of it. He practices a minimum of two hours per day to keep his skills honed.",
    "As Hawkeye, Barton possesses a custom-made bow, quick-release quiver, a number of trick arrows and a combat knife. Although he is not known to use melee weapons, Barton's incredible reflexes and hand-eye coordination allow him to easily master most weapons. He also received training in swordsmanship during his youth from the original Swordsman, who was considered one of the greatest experts in sword-fighting the world has ever known. Barton is skilled with swords, knives, nunchakus, staffs, and is one of the few people to be able to properly handle Captain America's shield",

    "Although Hawkeye became romantically involved with the Black Widow, he was unhappy being a criminal. When he approached the Avengers and told them of his desire to reform, Iron Man sponsored his membership on the team. Barton formed, along with Captain America, Scarlet Witch and her brother, Quicksilver, an incarnation of the Avengers known as Cap's Kooky Quartet. Eventually, however, Hawkeye came to respect Cap more than any other Avenger and became one of his staunchest supporters.",
  ],
  [
    "Widow ipsum dolor sit amet consectetur adipisicing elit. Natus facilis rerum sint accusantium? Blanditiis voluptates cum qui, quas eveniet iste. Qui hic incidunt cumque corporis adipisci cupiditate tenetur quisquam. Ea consequatur sunt illo beatae cumque accusamus nostrum similique! Natus porro minus dolor vel obcaecati deserunt hic deleniti maxime iure totam!",

    "Clint Barton was locked in the cell at the investigation site, while Nick Fury ordered scientists to examine Thor's body, learning that Thor was not a human. Phil Coulson told Fury that Barton insisted that he did not kill Thor and he never misfires, no matter what evidence S.H.I.E.L.D. had against him. While Barton was in the cell, Yellowjacket killed him by flying into his ear and causing a hemorrhage in his brain.",

    "Clint and Natasha are best friends. However, at the start of their relationship, Clint Barton (as Hawkeye) was sent to eliminate Natasha, but instead, Barton saw her skills and recommended her recruitment. The two began an everlasting partnership, with Barton affectionately calling her Nat.During The Avengers, Barton was taken by Loki Laufeyson, while being under his mind control. When she heard he was in danger, she immediately beat up her interogators.",
    "Barton has trained himself to become a master archer specializing in the use of regular bows, longbows, compound bows, and crossbows with near-perfect accuracy. He is capable of firing multiple arrows at a single target in a few seconds, hitting multiple targets in a few quick strokes, and directly hit small targets in the greatest of distances. Barton has even been known to hit an apple in the center of it. He practices a minimum of two hours per day to keep his skills honed.",
    "As Hawkeye, Barton possesses a custom-made bow, quick-release quiver, a number of trick arrows and a combat knife. Although he is not known to use melee weapons, Barton's incredible reflexes and hand-eye coordination allow him to easily master most weapons. He also received training in swordsmanship during his youth from the original Swordsman, who was considered one of the greatest experts in sword-fighting the world has ever known. Barton is skilled with swords, knives, nunchakus, staffs, and is one of the few people to be able to properly handle Captain America's shield",

    "Although Hawkeye became romantically involved with the Black Widow, he was unhappy being a criminal. When he approached the Avengers and told them of his desire to reform, Iron Man sponsored his membership on the team. Barton formed, along with Captain America, Scarlet Witch and her brother, Quicksilver, an incarnation of the Avengers known as Cap's Kooky Quartet. Eventually, however, Hawkeye came to respect Cap more than any other Avenger and became one of his staunchest supporters.",
  ],
  [
    "Widow ipsum dolor sit amet consectetur adipisicing elit. Natus facilis rerum sint accusantium? Blanditiis voluptates cum qui, quas eveniet iste. Qui hic incidunt cumque corporis adipisci cupiditate tenetur quisquam. Ea consequatur sunt illo beatae cumque accusamus nostrum similique! Natus porro minus dolor vel obcaecati deserunt hic deleniti maxime iure totam!",

    "Clint Barton was locked in the cell at the investigation site, while Nick Fury ordered scientists to examine Thor's body, learning that Thor was not a human. Phil Coulson told Fury that Barton insisted that he did not kill Thor and he never misfires, no matter what evidence S.H.I.E.L.D. had against him. While Barton was in the cell, Yellowjacket killed him by flying into his ear and causing a hemorrhage in his brain.",

    "Clint and Natasha are best friends. However, at the start of their relationship, Clint Barton (as Hawkeye) was sent to eliminate Natasha, but instead, Barton saw her skills and recommended her recruitment. The two began an everlasting partnership, with Barton affectionately calling her Nat.During The Avengers, Barton was taken by Loki Laufeyson, while being under his mind control. When she heard he was in danger, she immediately beat up her interogators.",
    "Barton has trained himself to become a master archer specializing in the use of regular bows, longbows, compound bows, and crossbows with near-perfect accuracy. He is capable of firing multiple arrows at a single target in a few seconds, hitting multiple targets in a few quick strokes, and directly hit small targets in the greatest of distances. Barton has even been known to hit an apple in the center of it. He practices a minimum of two hours per day to keep his skills honed.",
    "As Hawkeye, Barton possesses a custom-made bow, quick-release quiver, a number of trick arrows and a combat knife. Although he is not known to use melee weapons, Barton's incredible reflexes and hand-eye coordination allow him to easily master most weapons. He also received training in swordsmanship during his youth from the original Swordsman, who was considered one of the greatest experts in sword-fighting the world has ever known. Barton is skilled with swords, knives, nunchakus, staffs, and is one of the few people to be able to properly handle Captain America's shield",

    "Although Hawkeye became romantically involved with the Black Widow, he was unhappy being a criminal. When he approached the Avengers and told them of his desire to reform, Iron Man sponsored his membership on the team. Barton formed, along with Captain America, Scarlet Witch and her brother, Quicksilver, an incarnation of the Avengers known as Cap's Kooky Quartet. Eventually, however, Hawkeye came to respect Cap more than any other Avenger and became one of his staunchest supporters.",
  ],
  [
    "Widow ipsum dolor sit amet consectetur adipisicing elit. Natus facilis rerum sint accusantium? Blanditiis voluptates cum qui, quas eveniet iste. Qui hic incidunt cumque corporis adipisci cupiditate tenetur quisquam. Ea consequatur sunt illo beatae cumque accusamus nostrum similique! Natus porro minus dolor vel obcaecati deserunt hic deleniti maxime iure totam!",

    "Clint Barton was locked in the cell at the investigation site, while Nick Fury ordered scientists to examine Thor's body, learning that Thor was not a human. Phil Coulson told Fury that Barton insisted that he did not kill Thor and he never misfires, no matter what evidence S.H.I.E.L.D. had against him. While Barton was in the cell, Yellowjacket killed him by flying into his ear and causing a hemorrhage in his brain.",

    "Clint and Natasha are best friends. However, at the start of their relationship, Clint Barton (as Hawkeye) was sent to eliminate Natasha, but instead, Barton saw her skills and recommended her recruitment. The two began an everlasting partnership, with Barton affectionately calling her Nat.During The Avengers, Barton was taken by Loki Laufeyson, while being under his mind control. When she heard he was in danger, she immediately beat up her interogators.",
    "Barton has trained himself to become a master archer specializing in the use of regular bows, longbows, compound bows, and crossbows with near-perfect accuracy. He is capable of firing multiple arrows at a single target in a few seconds, hitting multiple targets in a few quick strokes, and directly hit small targets in the greatest of distances. Barton has even been known to hit an apple in the center of it. He practices a minimum of two hours per day to keep his skills honed.",
    "As Hawkeye, Barton possesses a custom-made bow, quick-release quiver, a number of trick arrows and a combat knife. Although he is not known to use melee weapons, Barton's incredible reflexes and hand-eye coordination allow him to easily master most weapons. He also received training in swordsmanship during his youth from the original Swordsman, who was considered one of the greatest experts in sword-fighting the world has ever known. Barton is skilled with swords, knives, nunchakus, staffs, and is one of the few people to be able to properly handle Captain America's shield",

    "Although Hawkeye became romantically involved with the Black Widow, he was unhappy being a criminal. When he approached the Avengers and told them of his desire to reform, Iron Man sponsored his membership on the team. Barton formed, along with Captain America, Scarlet Witch and her brother, Quicksilver, an incarnation of the Avengers known as Cap's Kooky Quartet. Eventually, however, Hawkeye came to respect Cap more than any other Avenger and became one of his staunchest supporters.",
  ],
  [
    "Widow ipsum dolor sit amet consectetur adipisicing elit. Natus facilis rerum sint accusantium? Blanditiis voluptates cum qui, quas eveniet iste. Qui hic incidunt cumque corporis adipisci cupiditate tenetur quisquam. Ea consequatur sunt illo beatae cumque accusamus nostrum similique! Natus porro minus dolor vel obcaecati deserunt hic deleniti maxime iure totam!",

    "Clint Barton was locked in the cell at the investigation site, while Nick Fury ordered scientists to examine Thor's body, learning that Thor was not a human. Phil Coulson told Fury that Barton insisted that he did not kill Thor and he never misfires, no matter what evidence S.H.I.E.L.D. had against him. While Barton was in the cell, Yellowjacket killed him by flying into his ear and causing a hemorrhage in his brain.",

    "Clint and Natasha are best friends. However, at the start of their relationship, Clint Barton (as Hawkeye) was sent to eliminate Natasha, but instead, Barton saw her skills and recommended her recruitment. The two began an everlasting partnership, with Barton affectionately calling her Nat.During The Avengers, Barton was taken by Loki Laufeyson, while being under his mind control. When she heard he was in danger, she immediately beat up her interogators.",
    "Barton has trained himself to become a master archer specializing in the use of regular bows, longbows, compound bows, and crossbows with near-perfect accuracy. He is capable of firing multiple arrows at a single target in a few seconds, hitting multiple targets in a few quick strokes, and directly hit small targets in the greatest of distances. Barton has even been known to hit an apple in the center of it. He practices a minimum of two hours per day to keep his skills honed.",
    "As Hawkeye, Barton possesses a custom-made bow, quick-release quiver, a number of trick arrows and a combat knife. Although he is not known to use melee weapons, Barton's incredible reflexes and hand-eye coordination allow him to easily master most weapons. He also received training in swordsmanship during his youth from the original Swordsman, who was considered one of the greatest experts in sword-fighting the world has ever known. Barton is skilled with swords, knives, nunchakus, staffs, and is one of the few people to be able to properly handle Captain America's shield",

    "Although Hawkeye became romantically involved with the Black Widow, he was unhappy being a criminal. When he approached the Avengers and told them of his desire to reform, Iron Man sponsored his membership on the team. Barton formed, along with Captain America, Scarlet Witch and her brother, Quicksilver, an incarnation of the Avengers known as Cap's Kooky Quartet. Eventually, however, Hawkeye came to respect Cap more than any other Avenger and became one of his staunchest supporters.",
  ],
  [
    "Widow ipsum dolor sit amet consectetur adipisicing elit. Natus facilis rerum sint accusantium? Blanditiis voluptates cum qui, quas eveniet iste. Qui hic incidunt cumque corporis adipisci cupiditate tenetur quisquam. Ea consequatur sunt illo beatae cumque accusamus nostrum similique! Natus porro minus dolor vel obcaecati deserunt hic deleniti maxime iure totam!",

    "Clint Barton was locked in the cell at the investigation site, while Nick Fury ordered scientists to examine Thor's body, learning that Thor was not a human. Phil Coulson told Fury that Barton insisted that he did not kill Thor and he never misfires, no matter what evidence S.H.I.E.L.D. had against him. While Barton was in the cell, Yellowjacket killed him by flying into his ear and causing a hemorrhage in his brain.",

    "Clint and Natasha are best friends. However, at the start of their relationship, Clint Barton (as Hawkeye) was sent to eliminate Natasha, but instead, Barton saw her skills and recommended her recruitment. The two began an everlasting partnership, with Barton affectionately calling her Nat.During The Avengers, Barton was taken by Loki Laufeyson, while being under his mind control. When she heard he was in danger, she immediately beat up her interogators.",
    "Barton has trained himself to become a master archer specializing in the use of regular bows, longbows, compound bows, and crossbows with near-perfect accuracy. He is capable of firing multiple arrows at a single target in a few seconds, hitting multiple targets in a few quick strokes, and directly hit small targets in the greatest of distances. Barton has even been known to hit an apple in the center of it. He practices a minimum of two hours per day to keep his skills honed.",
    "As Hawkeye, Barton possesses a custom-made bow, quick-release quiver, a number of trick arrows and a combat knife. Although he is not known to use melee weapons, Barton's incredible reflexes and hand-eye coordination allow him to easily master most weapons. He also received training in swordsmanship during his youth from the original Swordsman, who was considered one of the greatest experts in sword-fighting the world has ever known. Barton is skilled with swords, knives, nunchakus, staffs, and is one of the few people to be able to properly handle Captain America's shield",

    "Although Hawkeye became romantically involved with the Black Widow, he was unhappy being a criminal. When he approached the Avengers and told them of his desire to reform, Iron Man sponsored his membership on the team. Barton formed, along with Captain America, Scarlet Witch and her brother, Quicksilver, an incarnation of the Avengers known as Cap's Kooky Quartet. Eventually, however, Hawkeye came to respect Cap more than any other Avenger and became one of his staunchest supporters.",
  ],
  [
    "Widow ipsum dolor sit amet consectetur adipisicing elit. Natus facilis rerum sint accusantium? Blanditiis voluptates cum qui, quas eveniet iste. Qui hic incidunt cumque corporis adipisci cupiditate tenetur quisquam. Ea consequatur sunt illo beatae cumque accusamus nostrum similique! Natus porro minus dolor vel obcaecati deserunt hic deleniti maxime iure totam!",

    "Clint Barton was locked in the cell at the investigation site, while Nick Fury ordered scientists to examine Thor's body, learning that Thor was not a human. Phil Coulson told Fury that Barton insisted that he did not kill Thor and he never misfires, no matter what evidence S.H.I.E.L.D. had against him. While Barton was in the cell, Yellowjacket killed him by flying into his ear and causing a hemorrhage in his brain.",

    "Clint and Natasha are best friends. However, at the start of their relationship, Clint Barton (as Hawkeye) was sent to eliminate Natasha, but instead, Barton saw her skills and recommended her recruitment. The two began an everlasting partnership, with Barton affectionately calling her Nat.During The Avengers, Barton was taken by Loki Laufeyson, while being under his mind control. When she heard he was in danger, she immediately beat up her interogators.",
    "Barton has trained himself to become a master archer specializing in the use of regular bows, longbows, compound bows, and crossbows with near-perfect accuracy. He is capable of firing multiple arrows at a single target in a few seconds, hitting multiple targets in a few quick strokes, and directly hit small targets in the greatest of distances. Barton has even been known to hit an apple in the center of it. He practices a minimum of two hours per day to keep his skills honed.",
    "As Hawkeye, Barton possesses a custom-made bow, quick-release quiver, a number of trick arrows and a combat knife. Although he is not known to use melee weapons, Barton's incredible reflexes and hand-eye coordination allow him to easily master most weapons. He also received training in swordsmanship during his youth from the original Swordsman, who was considered one of the greatest experts in sword-fighting the world has ever known. Barton is skilled with swords, knives, nunchakus, staffs, and is one of the few people to be able to properly handle Captain America's shield",

    "Although Hawkeye became romantically involved with the Black Widow, he was unhappy being a criminal. When he approached the Avengers and told them of his desire to reform, Iron Man sponsored his membership on the team. Barton formed, along with Captain America, Scarlet Witch and her brother, Quicksilver, an incarnation of the Avengers known as Cap's Kooky Quartet. Eventually, however, Hawkeye came to respect Cap more than any other Avenger and became one of his staunchest supporters.",
  ],
];

export default BodyContent;
